## Create dataset

## Instructions:
create testing folder in home (~/) directory 

download glove embeddings and place "glove.6B" folder in home~/ directory http://nlp.stanford.edu/data/glove.6B.zip

also, increase the speed of your instance (i used 16 CPUs and it took 6 hours to train 1 epoch of 3,000 word sequences)

In [19]:
# !pip install keras
# !pip install tensorflow
# !pip install plotly
# !pip install gensim
# !pip install Word2Vec
# !pip install get_tmpfile
# !pip install gensim.test.utils
# !pip install boto
# !pip install google-compute-engine



    100% |████████████████████████████████| 51kB 19.9MB/s ta 0:00:01
  Running setup.py bdist_wheel for google-compute-engine ... done
  Stored in directory: /home/raymondleemids/.cache/pip/wheels/92/dc/36/aa22b839bc0f34908e2a9d5ac92ecb8a7e55d900da1faf144b
Successfully built google-compute-engine
You are using pip version 18.0, however version 18.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.


In [2]:
# Keras
from keras.preprocessing.text import Tokenizer
from keras.preprocessing.sequence import pad_sequences
from keras.models import Sequential
from keras.layers import Dense, Flatten, LSTM, Conv1D, MaxPooling1D, Dropout, Activation
from keras.layers.embeddings import Embedding
from keras.models import model_from_json
from keras.preprocessing.text import text_to_word_sequence






## Plot
import plotly.offline as py
import plotly.graph_objs as go
py.init_notebook_mode(connected=True)
import matplotlib as plt
# import matplotlib.pyplot

# NLTK
import nltk
from nltk.corpus import stopwords
nltk.download('stopwords')
from nltk.stem import SnowballStemmer


# Other
import re
import string
import numpy as np
import pandas as pd
from sklearn.manifold import TSNE
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import LabelBinarizer
from sklearn.model_selection import train_test_split
from sklearn.utils import shuffle
# from numpy import util


# Word2Vec
from gensim.test.utils import common_texts, get_tmpfile # not working
from gensim.models import Word2Vec

import re
from collections import Counter
import os









/home/raymondleemids/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.


[nltk_data] Downloading package stopwords to
[nltk_data]     /home/raymondleemids/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


## [Skip this section] Split Dataset Train/Test 

In [5]:
#load and read final.csv
# final_csv.to_csv('final.csv')
# final_csv = pd.read_csv('final.csv')

In [4]:
# final_csv[:5]

Unnamed: 0  Unnamed: 0.1  \
0           0             0   
1           1             2   
2           2             3   
3           3             4   
4           4             6   

                                          8K_Content  Adj Close_GSPC  \
0  ==============================================...          953.99   
1  Table of ContentsDate of report (Date of earli...          937.43   
2  Table of Contents  Table of ContentsItems 1 th...          843.32   
3  Table of ContentsDate of report (Date of earli...          882.50   
4  Table of ContentsDate of report (Date of earli...          843.59   

   Adj Close_stock  Close_GSPC  Close_stock        Date  Day Change_GSPC  \
0            12.56      953.99        13.04  2002-07-03             5.90   
1            14.18      937.43        14.73  2002-08-20           -13.27   
2            11.56      843.32        12.00  2002-09-19           -26.14   
3            11.31      882.50        11.75  2002-10-24           -13.64   
4            12.71      843.59        13.20  2003-02-05            -4.61   

   Day Change_stock                        ...                          \
0              0.71                        ...                           
1              0.06                        ...                           
2              0.04                        ...                           
3              0.27                        ...                           
4             -0.11                        ...                           

   Overnight Change_stock  Overnight Change_stock percentage  Ticker  \
0                   -0.23                          -0.018312    CSCO   
1                   -0.05                          -0.003397    CSCO   
2                   -0.54                          -0.043200    CSCO   
3                    0.22                           0.019538    CSCO   
4                    0.11                           0.008333    CSCO   

           Time    Time_of_day   Volume_GSPC  Volume_stock    Year  \
0  2.002070e+13  out_of_market  1.527800e+09    77171300.0  2002.0   
1  2.002082e+13  out_of_market  1.308500e+09    60171900.0  2002.0   
2  2.002092e+13  out_of_market  1.524000e+09    80020200.0  2002.0   
3  2.002102e+13  out_of_market  1.700570e+09   122749300.0  2002.0   
4  2.003020e+13  out_of_market  1.450800e+09   115080200.0  2003.0   

   stock_overnight_movement_tag  \
0                          stay   
1                          stay   
2                          down   
3                          stay   
4                          stay   

                                  8K_Content_cleaned  
0  ['securities', 'and', 'exchange', 'commission'...  
1  ['table', 'of', 'contentsdate', 'of', 'report'...  
2  ['table', 'of', 'contents', 'table', 'of', 'co...  
3  ['table', 'of', 'contentsdate', 'of', 'report'...  
4  ['table', 'of', 'contentsdate', 'of', 'report'...  

[5 rows x 29 columns]

In [6]:
### loaded into csv
# # convert integers to dummy variables (i.e. one hot encoded)
# encoder = LabelBinarizer()
# sparse_labels = encoder.fit_transform(final_csv['stock_overnight_movement_tag'])

In [7]:
### loaded into csv
# encoder.classes_

array(['down', 'stay', 'up'], dtype='<U4')

In [8]:
### loaded into csv
# # create sparse label columns
# sparse_labels = pd.DataFrame(data=sparse_labels,columns=['down', 'stay', 'up'])

In [9]:
### loaded into csv
# final_csv['down'] = sparse_labels['down']
# final_csv['stay'] = sparse_labels['stay']
# final_csv['up'] = sparse_labels['up']


In [21]:
# randomize dataset order 
# final_csv = shuffle(final_csv)

In [22]:
# # output shuffled.csv
# final_csv.to_csv('final_shuffled.csv')

## Load final_shuffled.csv

In [23]:
# load final_shuffled.csv
# final_csv = pd.read_csv('final_shuffled.csv')

In [444]:
# # filter final_csv to only include 'out of market'
# backup_csv = final_csv # backup in case i want to revert back
# final_csv = final_csv[final_csv['Time_of_day'] == 'out_of_market']

In [ ]:
# downsample
# final_csv = pd.concat([final_csv[final_csv['down'] == 1], 
#      final_csv[final_csv['stay'] == 1].iloc[:10750], 
#     final_csv[final_csv['up'] == 1]])

In [ ]:
# final_csv.to_csv('final_downsampled.csv')

In [ ]:
final_csv = pd.read_csv('final_shuffled.csv')

## Create '8K_Content' sequences

In [24]:
# tokenize text. update this when you update sequence length

tokenizer = Tokenizer()
tokenizer.fit_on_texts(final_csv['8K_Content'])


seq_len = 300 # set sequence length
sequences = tokenizer.texts_to_sequences(final_csv['8K_Content'])
data = pad_sequences(sequences, 
                     maxlen=seq_len, padding='post', 
                     truncating='post') # takes about 5-10 mins

In [25]:
# vocab size
vocabulary_size = max(tokenizer.word_index.values())
vocabulary_size

926195

In [26]:
final_csv['8K_Content_sequences'] = data.tolist()

In [154]:
final_csv

Unnamed: 0  Unnamed: 0.1  Unnamed: 0.1.1  \
0            71271         71549          113043   
1             1256          1257            2091   
2            71040         71317          112681   
3            60387         60652           96036   
4            71914         72192          113869   
5            77203         77486          122336   
6           103120        103484          166119   
7            12432         12515           20063   
8            48794         49009           77713   
9            45247         45461           72355   
10           90809         91147          146934   
11           25224         25330           40293   
12           47532         47747           75654   
13           36039         36182           57347   
14           68714         68990          109174   
15           26027         26134           41544   
16           46941         47156           74901   
17           85208         85531          138217   
18           58038         58302           92444   
19           71671         71949          113563   
20           46005         46219           73563   
21           82471         82775          134078   
22            5359          5362            8651   
23           23224         23329           37211   
24            1860          1861            3067   
25          106586        106955          172223   
26           30547         30687           48723   
27           71014         71291          112639   
28           75070         75350          118911   
29           53476         53708           85167   
...            ...           ...             ...   
107426      106970        107339          172836   
107427       93016         93362          150287   
107428       71932         72210          113891   
107429       28693         28831           45537   
107430       85305         85628          138409   
107431       53707         53939           85525   
107432       83104         83410          135076   
107433      104724        105091          168844   
107434      103355        103719          166569   
107435        5311          5314            8599   
107436       67969         68245          107910   
107437       64925         65190          103200   
107438       62955         63220           99971   
107439       59735         60000           95001   
107440         769           770            1124   
107441       64820         65085          102992   
107442       67221         67493          106834   
107443       41090         41273           65362   
107444       16023         16107           25695   
107445       60263         60528           95831   
107446       44131         44345           70667   
107447       87498         87835          142007   
107448       37194         37345           59427   
107449       82386         82690          133923   
107450        6265          6345           10254   
107451       54886         55145           87427   
107452       76820         77103          121632   
107453      103694        104058          167207   
107454         860           861            1344   
107455       15795         15879           25342   

                                               8K_Content  Adj Close_GSPC  \
0       Item 12.      Disclosure of Results of Operati...         1095.42   
1       ==============================================...         1143.20   
2                     Check the appropriate box below ...         1372.18   
3         Check the appropriate box below if the Form ...         1055.33   
4        Check the appropriate box below if the Form 8...         1460.91   
5       UNITED STATES SECURITIES AND EXCHANGE COMMISSI...         1184.63   
6                    Check the appropriate box below i...         1324.09   
7       UNITED STATESSECURITIES AND EXCHANGE COMMISSIO...         1480.94   
8         Check the appropriate box below if the Form ...         1414.85   
9          Ch

In [171]:
# sum(final_csv['down'])

10751

In [172]:
# sum(final_csv['stay']) # there are 85,956 'stay' classes. will modify this to 10,750 to match down and up

85956

In [158]:
# sum(final_csv['up'])

10749

In [170]:
# final_csv[final_csv['stay'] == 1][:10750]

Unnamed: 0  Unnamed: 0.1  Unnamed: 0.1.1  \
0           71271         71549          113043   
1            1256          1257            2091   
3           60387         60652           96036   
5           77203         77486          122336   
6          103120        103484          166119   
7           12432         12515           20063   
8           48794         49009           77713   
9           45247         45461           72355   
10          90809         91147          146934   
11          25224         25330           40293   
13          36039         36182           57347   
14          68714         68990          109174   
15          26027         26134           41544   
16          46941         47156           74901   
17          85208         85531          138217   
18          58038         58302           92444   
19          71671         71949          113563   
21          82471         82775          134078   
22           5359          5362            8651   
23          23224         23329           37211   
24           1860          1861            3067   
25         106586        106955          172223   
27          71014         71291          112639   
28          75070         75350          118911   
29          53476         53708           85167   
31          32042         32182           50977   
32          55974         56236           89216   
33         103758        104122          167283   
34           3633          3634            6025   
35          51872         52099           82686   
...           ...           ...             ...   
13405       65770         66035          104546   
13406       75269         75549          119217   
13407       91759         92105          148689   
13409       21608         21701           34610   
13410       70389         70665          111677   
13411       63715         63980          101072   
13412       36310         36453           57764   
13413        6095          6098            9810   
13414       96878         97235          156436   
13415       38631         38814           61572   
13416       99000         99358          159882   
13417       39447         39630           62713   
13419       47214         47429           75265   
13420       25737         25843           41045   
13422       54067         54326           86090   
13424       28072         28179           44604   
13425       92729         93075          149876   
13426         300           300             440   
13427        6398          6478           10437   
13429       55017         55276           87620   
13430      107146        107515          173029   
13431       95860         96215          154846   
13432       66643         66914          105883   
13433        5431          5434            8740   
13434       40368         40551           64193   
13435       37186         37337           59416   
13436       10912         10995           17786   
13437       25873         25980           41218   
13438       50874         51098           81077   
13441       94944         95299          153420   

                                              8K_Content  Adj Close_GSPC  \
0      Item 12.      Disclosure of Results of Operati...         1095.42   
1      ==============================================...         1143.20   
3        Check the appropriate box below if the Form ...         1055.33   
5      UNITED STATES SECURITIES AND EXCHANGE COMMISSI...         1184.63   
6                   Check the appropriate box below i...         1324.09   
7      UNITED STATESSECURITIES AND EXCHANGE COMMISSIO...         1480.94   
8        Check the appropriate box below if the Form ...         1414.85   
9         Check the appropriate box below if the Form...         1379.93   
10                ITEM 7.    FINANCIAL STATEMENTS AND...          984.03   
11     SECURITIES AND EXCHANGE COMMISSION Washington,...          901.58   
13      

In [174]:
# downsample_csv = pd.concat([final_csv[final_csv['down'] == 1], 
#      final_csv[final_csv['stay'] == 1][:10750], 
#     final_csv[final_csv['up'] == 1]])

In [175]:
# sum(downsample_csv['down'])

10751

In [176]:
# sum(downsample_csv['stay'])

10750

In [177]:
# sum(downsample_csv['up'])

10749

In [53]:
downsampled_csv = pd.concat([final_csv[final_csv['down'] == 1], 
     final_csv[final_csv['stay'] == 1][:10750], 
    final_csv[final_csv['up'] == 1]])

NameError: name 'final_csv' is not defined

In [42]:
# downsampled_csv[downsampled_csv['Year'] < 2011]['Industry'].groupby(downsampled_csv['Industry']).describe()
# downsampled_csv['Industry'].groupby(downsampled_csv['Industry']).describe()

count unique                         top  freq
Industry                                                                 
Consumer Discretionary      6235      1      Consumer Discretionary  6235
Consumer Staples            1463      1            Consumer Staples  1463
Energy                      1764      1                      Energy  1764
Financials                  4674      1                  Financials  4674
Health Care                 3586      1                 Health Care  3586
Industrials                 3995      1                 Industrials  3995
Information Technology      7433      1      Information Technology  7433
Materials                   1764      1                   Materials  1764
Telecommunication Services   298      1  Telecommunication Services   298
Utilities                   1038      1                   Utilities  1038

In [52]:
downsampled_csv = pd.concat([downsampled_csv[downsampled_csv['Industry'] == 'Consumer Discretionary'].iloc[:3000], 
                              downsampled_csv[downsampled_csv['Industry'] == 'Consumer Staples'].iloc[:3000],
                              downsampled_csv[downsampled_csv['Industry'] == 'Consumer Staples'].iloc[:3000],
                              downsampled_csv[downsampled_csv['Industry'] == 'Consumer Staples'].iloc[:74],
                              downsampled_csv[downsampled_csv['Industry'] == 'Energy'].iloc[:3000], 
                              downsampled_csv[downsampled_csv['Industry'] == 'Energy'].iloc[:1236], 
                              downsampled_csv[downsampled_csv['Industry'] == 'Financials'].iloc[:3000], 
                              downsampled_csv[downsampled_csv['Industry'] == 'Health Care'].iloc[:3000], 
                              downsampled_csv[downsampled_csv['Industry'] == 'Industrials'].iloc[:3000],
                              downsampled_csv[downsampled_csv['Industry'] == 'Information Technology'].iloc[:3000],
                              downsampled_csv[downsampled_csv['Industry'] == 'Materials'].iloc[:3000], 
                              downsampled_csv[downsampled_csv['Industry'] == 'Materials'].iloc[:1236], 
                              downsampled_csv[downsampled_csv['Industry'] == 'Telecommunication Services'].iloc[:3000], 
                              downsampled_csv[downsampled_csv['Industry'] == 'Telecommunication Services'].iloc[:3000], 
                              downsampled_csv[downsampled_csv['Industry'] == 'Telecommunication Services'].iloc[:3000], 
                              downsampled_csv[downsampled_csv['Industry'] == 'Telecommunication Services'].iloc[:3000], 
                              downsampled_csv[downsampled_csv['Industry'] == 'Telecommunication Services'].iloc[:3000], 
                              downsampled_csv[downsampled_csv['Industry'] == 'Telecommunication Services'].iloc[:3000], 
                              downsampled_csv[downsampled_csv['Industry'] == 'Telecommunication Services'].iloc[:3000], 
                              downsampled_csv[downsampled_csv['Industry'] == 'Telecommunication Services'].iloc[:3000], 
                              downsampled_csv[downsampled_csv['Industry'] == 'Telecommunication Services'].iloc[:3000], 
                              downsampled_csv[downsampled_csv['Industry'] == 'Telecommunication Services'].iloc[:3000], 
                              downsampled_csv[downsampled_csv['Industry'] == 'Telecommunication Services'].iloc[:20],  
                              downsampled_csv[downsampled_csv['Industry'] == 'Utilities'].iloc[:4000], 
                              downsampled_csv[downsampled_csv['Industry'] == 'Utilities'].iloc[:4000], 
                              downsampled_csv[downsampled_csv['Industry'] == 'Utilities'].iloc[:924]])

In [50]:
# downsampled_test['Industry'].groupby(downsampled_test['Industry']).describe()

count unique                         top  freq
Industry                                                                 
Consumer Discretionary      3000      1      Consumer Discretionary  3000
Consumer Staples            3000      1            Consumer Staples  3000
Energy                      3000      1                      Energy  3000
Financials                  3000      1                  Financials  3000
Health Care                 3000      1                 Health Care  3000
Industrials                 3000      1                 Industrials  3000
Information Technology      3000      1      Information Technology  3000
Materials                   3000      1                   Materials  3000
Telecommunication Services  3000      1  Telecommunication Services  3000
Utilities                   3000      1                   Utilities  3000

In [ ]:
final_csv = downsampled_csv

In [ ]:
final_csv['8K_Content_sequences'] = final_csv['8K_Content_sequences'].tolist()

In [27]:
# 02-08 train. 09-10 develoment, 11-12 test
# X_train = final_csv['8K_Content_cleaned'][final_csv['Year'] <= 2008]
# X_dev = final_csv['8K_Content_cleaned'][(final_csv['Year'] >= 2009) & 
#                                        (final_csv['Year'] <= 2010)]
# X_test = final_csv['8K_Content_cleaned'][final_csv['Year'] >= 2011]

X_train = final_csv['8K_Content_sequences'][final_csv['Year'] <= 2008]
X_dev = final_csv['8K_Content_sequences'][(final_csv['Year'] >= 2009) & 
                                       (final_csv['Year'] <= 2010)]
X_test = final_csv['8K_Content_sequences'][final_csv['Year'] >= 2011]

y_train = final_csv[['down','stay','up']][final_csv['Year'] <= 2008]
y_dev = final_csv[['down','stay','up']][(final_csv['Year'] >= 2009) & 
                                       (final_csv['Year'] <= 2010)]
y_test = final_csv[['down','stay','up']][final_csv['Year'] >= 2011]

## Build and Train LSTM Model

In [ ]:
# TODO: add Tensorboard

# reload(rnnlm)

# TF_GRAPHDIR = "/tmp/w266_project/finance_text_graph"

# # Clear old log directory.
# shutil.rmtree(TF_GRAPHDIR, ignore_errors=True)

# lm = rnnlm.RNNLM(V=10000, H=200, num_layers=2)
# lm.BuildCoreGraph()
# lm.BuildTrainGraph()
# lm.BuildSamplerGraph()

# summary_writer = tf.summary.FileWriter(TF_GRAPHDIR, lm.graph)


In [508]:
# TODO: update arbitary parameters, such as input_length
# build network

model_lstm = Sequential()
model_lstm.add(Embedding(vocabulary_size, 100, input_length=seq_len))
model_lstm.add(LSTM(100, dropout=0.5, recurrent_dropout=0.5))
model_lstm.add(Dense(3, activation='softmax'))
model_lstm.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [493]:
# np.array(X_train[:5].values.tolist()).shape

(5, 300)

In [497]:
# np.array(y_train[:5].values.tolist()).shape

(5, 3)

In [499]:
# y_train[:5].values.shape

(57616, 3)

In [506]:
# np.array(y_train[:5].values).shape

(5, 3)

In [513]:
# train network

# model_lstm.fit(np.array(X_train[:5].values.tolist()), np.array(y_train[:5].values.tolist()), validation_split=0.4, epochs=5)

model_lstm.fit(np.array(X_train.values.tolist()), 
               np.array(y_train.values.tolist()), 
               validation_data=(np.array(X_dev.values.tolist()), 
                                np.array(y_dev.values.tolist())), 
               epochs=10)

#TODO: change validation split to validation_data

# takes about 3 mins per epoch using 2/3 of full dataset
# takes about 3 hours per epoch using full dataset (less testing set) 


Train on 5000 samples, validate on 5000 samples
Epoch 1/5
5000/5000 [==============================] - 203s 41ms/step - loss: 0.6128 - acc: 0.8014 - val_loss: 0.6554 - val_acc: 0.7650
Epoch 2/5
5000/5000 [==============================] - 207s 41ms/step - loss: 0.5251 - acc: 0.8060 - val_loss: 0.6870 - val_acc: 0.7630
Epoch 3/5
5000/5000 [==============================] - 205s 41ms/step - loss: 0.4711 - acc: 0.8192 - val_loss: 0.6918 - val_acc: 0.7492
Epoch 4/5
5000/5000 [==============================] - 211s 42ms/step - loss: 0.4387 - acc: 0.8350 - val_loss: 0.8411 - val_acc: 0.7584
Epoch 5/5
5000/5000 [==============================] - 206s 41ms/step - loss: 0.4113 - acc: 0.8456 - val_loss: 0.7785 - val_acc: 0.7342


In [517]:
# test network

model_lstm.evaluate(np.array(X_test.values.tolist()), 
                    np.array(y_test.values.tolist()))
                    

500/500 [==============================] - 1s 3ms/step


[0.6086614561080933, 0.8040000004768372]

In [518]:
# predict
model_lstm_preds = model_lstm.predict(np.array(X_test.values.tolist()))

In [523]:
# display prediction probs
# model_lstm_preds[:5]

array([[0.02170856, 0.02878717, 0.94950426],
       [0.5008816 , 0.1591925 , 0.33992592],
       [0.02305297, 0.03035573, 0.9465913 ],
       [0.02603913, 0.04997493, 0.92398596],
       [0.00454127, 0.00218268, 0.9932761 ]], dtype=float32)

In [197]:
# set model # for saving the model and weights to json and h5
model_num = 6

In [552]:
# predictions to csv
np.savetxt('predictions_lstm_%d.csv' %model_num, model_lstm_preds, delimiter=',')
print("Saved predictions to disk: ", 'predictions_lstm_%d.csv' %model_num)

In [532]:
# display prediction
np.argmax(model_lstm_preds, axis=1)

array([2, 0, 2, 2, 2])

In [536]:
# display actuals
np.argmax(np.array(y_test), axis=1)

array([2, 0, 2, 2, 2])

In [540]:
# prediction counts ['down','stay','up']
np.bincount(np.argmax(model_lstm_preds, axis=1))

array([  7,  36, 457])

In [544]:
# actual counts ['down', stay', 'up']
np.bincount(np.argmax(np.array(y_test), axis=1))

array([ 46,  49, 405])

In [550]:
# save model

# serialize model to JSON
model_lstm_json = model_lstm.to_json()
with open("model_lstm_%d.json" %model_num, "w") as json_file:
    json_file.write(model_lstm_json)
# serialize weights to HDF5
model_lstm.save_weights("model_lstm_%d.h5" %model_num)
print("Saved model to disk: ", 'model_lstm_%d.json and model_lstm_%d.h5' %(model_num, model_num))

Saved model to disk


In [ ]:
# load model
# note: latest file updated 11/30. 3,000 word sequence.

# load json and create model
json_file = open('model_lstm_%d.json' %model_num, 'r')
loaded_model_json = json_file.read()
json_file.close()
loaded_model = model_from_json(loaded_model_json)

# load weights into new model
loaded_model.load_weights("model_lstm_%d.h5" %model_num)
print("Loaded model from disk: ", 'model_lstm_%d.json and model_lstm_%d.h5' %(model_num, model_num))

In [266]:
# evaluate loaded model on test data
loaded_model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
# loaded_model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
score = loaded_model.evaluate(np.array(X_test.values.tolist()), 
                              np.array(y_test.values.tolist()), verbose=0)
print("%s: %.2f%%" % (loaded_model.metrics_names[1], score[1]*100))

acc: 53.18%


In [267]:
# loaded_model.predict(X_test)

array([[1.],
       [1.],
       [1.],
       ...,
       [1.],
       [1.],
       [1.]], dtype=float32)

## LSTM with 1D Convolutional Layer

In [117]:
def create_conv_model():
    model_conv = Sequential()
    model_conv.add(Embedding(vocabulary_size, 100, input_length=seq_len))
    model_conv.add(Dropout(0.5))
    model_conv.add(Conv1D(64, 5, activation='relu'))
    model_conv.add(MaxPooling1D(pool_size=4))
    model_conv.add(LSTM(100))
    model_conv.add(Dense(3, activation='softmax'))
    model_conv.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
    return model_conv

In [118]:
model_conv = create_conv_model()
model_conv.fit(np.array(X_train.values.tolist()), 
               np.array(y_train.values.tolist()), 
               validation_data=(np.array(X_dev.values.tolist()), 
                                np.array(y_dev.values.tolist())), 
               epochs=10)

Train on 66848 samples, validate on 44566 samples
Epoch 1/10
66848/66848 [==============================] - 127s 2ms/step - loss: 7.3688 - acc: 0.5378 - val_loss: 7.3970 - val_acc: 0.5360
Epoch 2/10
66848/66848 [==============================] - 120s 2ms/step - loss: 7.3688 - acc: 0.5378 - val_loss: 7.3970 - val_acc: 0.5360
Epoch 3/10
66848/66848 [==============================] - 121s 2ms/step - loss: 7.3688 - acc: 0.5378 - val_loss: 7.3970 - val_acc: 0.5360
Epoch 4/10
66848/66848 [==============================] - 118s 2ms/step - loss: 7.3688 - acc: 0.5378 - val_loss: 7.3970 - val_acc: 0.5360
Epoch 5/10
66848/66848 [==============================] - 123s 2ms/step - loss: 7.3688 - acc: 0.5378 - val_loss: 7.3970 - val_acc: 0.5360
Epoch 6/10
66848/66848 [==============================] - 118s 2ms/step - loss: 7.3688 - acc: 0.5378 - val_loss: 7.3970 - val_acc: 0.5360
Epoch 7/10
66848/66848 [==============================] - 118s 2ms/step - loss: 7.3688 - acc: 0.5378 - val_loss: 7.3970 - 

In [119]:
model_conv.evaluate(np.array(X_train.values.tolist()), 
               np.array(y_train.values.tolist()))

111414/111414 [==============================] - 27s 239us/step


[7.380082198507702, 0.537077925569533]

In [120]:
model_conv_preds = model_conv.predict(np.array(X_test.values.tolist()))

array([1.], dtype=float32)

In [ ]:
# save predictions to csv
np.savetxt('predictions_conv_%d.csv' %model_num, model_conv_preds, delimiter=',')
print("Saved predictions to disk: ", 'predictions_conv_%d.csv' %model_num)

In [122]:
# # save model

model_conv_json = model_conv.to_json()
with open("model_conv_%d.json" %model_num, "w") as json_file:
    json_file.write(model_conv_json)
# serialize weights to HDF5
model_conv.save_weights("model_conv_%d.h5" %model_num)
print("Saved model to disk:", 'model_conv_%d.json and model_conv_%d.h5' %(model_num, model_num))

Saved model to disk


In [268]:
# load model

# load json and create model
json_file = open('model_conv_%d.json' %model_num, 'r')
loaded_model_json = json_file.read()
json_file.close()
loaded_model = model_from_json(loaded_model_json)

# load weights into new model
loaded_model.load_weights("model_conv_%d.h5" %model_num)
print("Loaded model from disk: ", 'model_conv_%d.json and model_conv_%d.h5' %(model_num, model_num))

Loaded model from disk


In [269]:
# evaluate loaded model on test data
loaded_model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
#loaded_model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
score = loaded_model.evaluate(np.array(X_test.values.tolist()), 
                              np.array(y_test.values.tolist()), verbose=0)
print("%s: %.2f%%" % (loaded_model.metrics_names[1], score[1]*100))

acc: 53.18%


In [270]:
# loaded_model.predict(X_test)

array([[1.],
       [1.],
       [1.],
       ...,
       [1.],
       [1.],
       [1.]], dtype=float32)

## Use pre-trained Glove word embeddings

In [29]:
# # load GLOVE embeddings
# embeddings_index = dict()
# f = open('~/glove.6B/glove.6B.100d.txt')
# for line in f:
#     values = line.split()
#     word = values[0]
#     coefs = np.asarray(values[1:], dtype='float32')
#     embeddings_index[word] = coefs
# f.close()
# print('Loaded %s word vectors.' % len(embeddings_index))

FileNotFoundError: [Errno 2] No such file or directory: '~/glove.6B/glove.6B.100d.txt'

In [114]:
# !cd ~/glove.6B

In [ ]:
# embeddings_index

In [ ]:
# # create a weight matrix for words in training docs
# embedding_matrix = np.zeros((vocabulary_size, 100))
# for word, index in tokenizer.word_index.items():
#     if index > vocabulary_size - 1:
#         break
#     else:
#         embedding_vector = embeddings_index.get(word)
#         if embedding_vector is not None:
#             embedding_matrix[index] = embedding_vector

In [ ]:
# # LSTM and CNN model
# model_glove = Sequential()
# model_glove.add(Embedding(vocabulary_size, 100, input_length=50, weights=[embedding_matrix], trainable=False))
# model_glove.add(Dropout(0.2))
# model_glove.add(Conv1D(64, 5, activation='relu'))
# model_glove.add(MaxPooling1D(pool_size=4))
# model_glove.add(LSTM(100))
# model_glove.add(Dense(1, activation='softmax'))
# model_glove.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [ ]:
# # train model
# model_glove.fit(data, merged_csv['movement'], validation_split=0.4, epochs=3)

In [ ]:
# # evaluate model
# model_glove.evaluate(data, merged_csv['movement'])

## Use Word2Vec to train word embeddings on corpus

In [ ]:
# from gensim.models import Word2Vec
# import nltk
# # nltk.download('punkt')

In [ ]:
# # tokenize financial data
# merged_csv['tokenized'] = merged_csv.apply(lambda row : nltk.word_tokenize(row['8K_Content_cleaned']), axis=1)


In [ ]:
# merged_csv.head()


In [ ]:
# #train
# model_w2v = Word2Vec(merged_csv['tokenized'], size=100)

In [ ]:
# X = model_w2v[model_w2v.wv.vocab]

In [ ]:
# X.shape

In [ ]:
# # Create LSTM and CNN model

# model_w2v = Sequential()
# model_w2v.add(Embedding(1925, 100, input_length=50, weights=[X], trainable=False))
# model_w2v.add(Dropout(0.2))
# model_w2v.add(Conv1D(64, 5, activation='relu'))
# model_w2v.add(MaxPooling1D(pool_size=4))
# model_w2v.add(LSTM(100))
# model_w2v.add(Dense(1, activation='softmax'))
# model_w2v.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [ ]:
# # train model
# model_w2v.fit(data, merged_csv['movement'], validation_split=0.4, epochs=3)


## Plot Word Vectors Using PCA

In [300]:
# from sklearn.decomposition import TruncatedSVD


In [301]:
# tsvd = TruncatedSVD(n_components=5, n_iter=10)
# result = tsvd.fit_transform(X)

In [302]:
# result.shape

(1925, 5)

In [304]:
# tsvd_word_list = []
# words = list(model_w2v.wv.vocab)
# for i, word in enumerate(words):
#     tsvd_word_list.append(word)

In [309]:
# len(words)

1925

In [311]:
# tsvd_word_list = []
# words = list(model_w2v.wv.vocab)
# for i, word in enumerate(words):
#     tsvd_word_list.append(word)

# trace = go.Scatter(
#     x = result[0:len(words), 0], 
#     y = result[0:len(words), 1],
#     mode = 'markers',
#     text= tsvd_word_list[0:len(words)]
# )

# layout = dict(title= 'SVD 1 vs SVD 2',
#               yaxis = dict(title='SVD 2'),
#               xaxis = dict(title='SVD 1'),
#               hovermode= 'closest')

# fig = dict(data = [trace], layout= layout)
# py.iplot(fig)

## Visualize word embeddings

In [247]:
# lstm_embds = model_lstm.layers[0].get_weights()[0]

In [248]:
# conv_embds = model_conv.layers[0].get_weights()[0]

In [249]:
# glove_emds = model_lstm.layers[0].get_weights()[0]

In [250]:
# word_list = []
# for word, i in tokenizer.word_index.items():
#     word_list.append(word)

In [251]:
# def plot_words(data, start, stop, step):
#     trace = go.Scatter(
#         x = data[start:stop:step,0], 
#         y = data[start:stop:step, 1],
#         mode = 'markers',
#         text= word_list[start:stop:step]
#     )
#     layout = dict(title= 't-SNE 1 vs t-SNE 2',
#                   yaxis = dict(title='t-SNE 2'),
#                   xaxis = dict(title='t-SNE 1'),
#                   hovermode= 'closest')
#     fig = dict(data = [trace], layout= layout)
#     py.iplot(fig)

In [252]:
# # LSTM embeddings 

# lstm_tsne_embds = TSNE(n_components=2).fit_transform(lstm_embds)

In [254]:
# plot_words(lstm_tsne_embds, 0, 2000, 1)


In [253]:
# # CNN + LSTM
# conv_tsne_embds = TSNE(n_components=2).fit_transform(conv_embds)


KeyboardInterrupt: 

In [ ]:
# plot_words(conv_tsne_embds, 0, 2000, 1)


In [255]:
# # Glove

# glove_tsne_embds = TSNE(n_components=2).fit_transform(glove_emds)


In [256]:
# plot_words(glove_tsne_embds, 0, 2000, 1)
